### ISSUE TITLE
Feature Request: Retrieve Instagram profile picture URLs

### ISSUE THREAD

**Issue by fThues** [scaramangagency/craftagram#10]
I need to display the user's profile picture along with the posts. Would it be possible to implement a function for retrieving the image URLs? Thanks!

**Comment by joshua-martin** [comment]
Unfortunately, the Basic Display API doesn't allow us to get the profile picture. The only information we can return for the user is seen at https://developers.facebook.com/docs/instagram-basic-display-api/reference/user.

Until Instagram return the profile picture URL as part of this response, this isn't something we can implement.

**Comment by fThues** [comment]
Right, this is what I just ran into when I started to implement the feature myself. Seems like a strange oversight on Instagram's part! I know that we can query `https://www.instagram.com/USERNAME/?__a=1` and get a result that includes the URLs, but it's not part of the Basic Display API, so I can understand if you don't want to rely on that.

Thanks for the quick reply!

**Comment by joshua-martin** [comment]
I hadn't realised you could grab data in that way without needing to interface with the API.

I will add a function to grab profile data from that URL, though as you say it does come with a caveat that it might stop being available at some point.

From that data, I can really only see the following information that is publicly available (that is, you can grab it regardless of private/public status), so I'll return this for use in a variable.
- Profile Picture (SD/HD)
- Follower Count
- Followers Count

**Comment by joshua-martin** [comment]
I've cut a release 1.1.0 that includes this data for you @fThues. Check the README for more info 👍

**Comment by fThues** [comment]
Wow, that was quick! Thanks a lot!
