### ISSUE TITLE
Issue: Getting oAuth Invalid Redirect URL error when trying to authorize

### ISSUE THREAD

**Issue by brianrivet** [scaramangagency/craftagram#11]
Hi,

I'm using Craftagram 1.1.0 on Craft 3.4.27. I have set up the Instagram feed as an app in Facebook per the instructions in the readme, but when I try to authorize in Craft I'm getting an error saying my redirect URL is invalid. I've double-checked it and it is set up according to the instructions. Can you please help me to resolve this issue?

Thanks!

Brian

**Comment by joshua-martin** [comment]
What do you have as your baseUrl?

**Comment by brianrivet** [comment]
My site is https://www.drinkmyhy.com. The redirect URL is set to: https://www.drinkmyhy.com/actions/craftagram/default/auth

**Comment by brianrivet** [comment]
Nevermind. My base url in the CP had a trailing slash. I've resolved the problem. Thanks for the fast response!

**Comment by joshua-martin** [comment]
Thanks @brianrivet. I had thought I fixed this in the latest release but apparently not! I'll take another look.
