### ISSUE TITLE
Add CP section

### ISSUE THREAD

**Issue by joshua-martin** [scaramangagency/craftagram#14]
> Another thing to consider though is how to connect / install the instagram on production environments which may have [allowAdminChanges: false ](https://docs.craftcms.com/v3/config/config-settings.html#allowadminchanges) — as you can't access or update settings section or plugins if this is set.

_Originally posted by @isjackwild in https://github.com/scaramangagency/craftagram/issues/12#issuecomment-659462066_

**Comment by mijewe** [comment]
It would also be useful to be able to assign Craftagram user permissions, so I can allow non-admins to hit the Authorise Craft button.

**Comment by joshua-martin** [comment]
Closed in [1.2.0](https://github.com/scaramangagency/craftagram/releases/tag/1.2.0).

@mijewe User permissions to access the CP section will be available under Permissions > General by default. You'll just need to tick it on for those non-admin users.

**Comment by isjackwild** [comment]
Just updated and these latest changes are really helpful, thanks!

One note though — perhaps it would be a good idea to hide the App ID and App Secret settings when allowAdminChanges => false. These two things you wouldn't want to be able to be changed in that scenario, but the authorise button you'd need in all environments. Just to prevent content managers from accidentally changing the API key ;)

**Comment by joshua-martin** [comment]
Why would you be giving access to generate the access token if they couldn't also modify the API credentials? In my opinion, either they would have access or not–once the token is generated, feasibly you should never need to authorise again.

Plus, if you're worried about token longevity you would use the refresh action.

**Comment by isjackwild** [comment]
It would be because you'd always need to click the authorize button once
per environment (for example, on my production environment, I do not allow
admin panel changes, but I'd still need to click to authorize the site when
I first install the plugin (or reauthorize if I change any settings, for
example)

**Comment by joshua-martin** [comment]
There's the real possibility that you could have different credentials for dev/staging/production. I appreciate the potential use-case but I don't think it's a required FR.

Thanks!

**Comment by isjackwild** [comment]
Okay no worries — the different credentials would be handled as environment variables ideally, but it's not a big issue either way. The current update is really helpful as it is already. :)
