### ISSUE TITLE
Update readme for minimum Craft version 3.1.0

### ISSUE THREAD

**Issue by mijewe** [scaramangagency/craftagram#15]
Hi,

I installed this on a Craft 3.0.x site, and got a "parseEnv doesn't exist" error.

According to the Craft changelog, parseEnv was only added in 3.1.0, so I had to update to get this to work.

The readme should be updated to reflect this.

Thanks!

https://github.com/craftcms/cms/blob/develop/CHANGELOG-v3.md#310---2019-01-15

**Comment by joshua-martin** [comment]
Closed in [1.2.0](https://github.com/scaramangagency/craftagram/releases/tag/1.2.0).
