### ISSUE TITLE
OAuthException - 400 - "Insufficient developer role"

### ISSUE THREAD

**Issue by strandofgenius** [scaramangagency/craftagram#16]
Hello,
I have followed the steps and get to the point of Authorizing Craft and it gives me the following. Is this because I haven't purchased the license yet? I was hoping I'd be able to test your plugin to make sure it works for me. Thanks.

```
error_type | "OAuthException"
code | 400
error_message | "Insufficient developer role"
```

**Comment by joshua-martin** [comment]
This is an issue with your set-up of instagram. There are no restrictions on using our plugin (and I believe it is against TOS to do so, anyway).

cc: https://stackoverflow.com/questions/58778302/instagram-display-api-insufficient-developer-role

**Comment by bigskillet** [comment]
I've had Craftagram up and running the past 60 days, but the cronjob failed. I tried to reauthorize using the "Authorize Craft" button, but it gives me the same error. Looking at the StackOverflow link, the tester account is already connected since it was running before. Since it was running before and everything is linked already, shouldn't it reauthorize and refresh the token with no issue?

**Comment by joshua-martin** [comment]
@bigskillet has the password changed on the account, possibly? The error is returned by Instagram, so the issue has to be a setup issue with the account, unfortunately.

Perhaps worth removing your test user from your application and running through the set up again and seeing if you still have the issue.

**Comment by bigskillet** [comment]
I was logged into an Instagram account that was different from the one connected to Craftagram. I assume it was pinging that account and getting the wrong login info, causing the error. Once I logged into the correct Instagram that was associated with Craftagram and the tester account, it reauthorized just fine. User error on my part. Took me a little while to wrap my head around it. I appreciate your reply.

**Comment by joshua-martin** [comment]
Cool, glad to hear you got it sorted 👍🏼
