### ISSUE TITLE
CP Section rendering only page partial (with no styling) on certain environments

### ISSUE THREAD

**Issue by isjackwild** [scaramangagency/craftagram#17]
On my live site, the CP section appears to load only the plain HTML of the inner (right hand) part of the Dashboard.

Inspecting the source, I can see that the only HTML rendered is that of the Craftagram section itself (second screenshot). I haven't experienced this issue before with other CP Sections (is it possibly to do with routing, as it redirects you to /craftagram/settings).

It doesn't work on the live server (Apache2) but it is working on Nginx for local development.

![image](https://user-images.githubusercontent.com/5766159/88281829-40324b80-cce0-11ea-81c8-9aceef1982e5.png)
![image](https://user-images.githubusercontent.com/5766159/88281927-72dc4400-cce0-11ea-8f3c-cee725b608cf.png)

**Comment by joshua-martin** [comment]
That's very odd–you're still seeing the old template. In `vendor/scaramangagency/craftagram` folder on your production website, what are you seeing in the `templates` folder?

**Comment by isjackwild** [comment]
I'm seeing this...

It may be because the build script might only add new files, and leave the old ones in place. I guess if I manually delete that `settings.twig` in the root of `templates/` it may fix things.

![image](https://user-images.githubusercontent.com/5766159/88282706-f6e2fb80-cce1-11ea-9ac8-dde6a4588e9f.png)

**Comment by isjackwild** [comment]
Just tried that, and it's fixed. Sorry my build must be set to merge folders rather than overwrite. Thanks for the pointer though!

**Comment by joshua-martin** [comment]
No problemo!
