### ISSUE TITLE
Can no longer manually add long access token

### ISSUE THREAD

**Issue by rbaud** [scaramangagency/craftagram#18]
Hello,

After updating to 1.2.3 we can no longer manually insert a Long Access Token as the field is disabled. The ability to manually insert a token has been very useful for testing in a staging environment (without a valid redirect_url set for Instagram). Was this an intentional change? Is there a workaround for manually adding a Long Access Token for testing?

**Comment by joshua-martin** [comment]
@rbaud Just an oversight really–I figured no one would really have a reason to need to modify their long access token. I have allowed this to be editable again in [1.2.4](https://github.com/scaramangagency/craftagram/releases/tag/1.2.4).

**Comment by rbaud** [comment]
Rad! Thanks so much for taking the time to address this. I appreciate it!
