### ISSUE TITLE
Invalid Scope

### ISSUE THREAD

**Issue by kaspar-allenbach** [scaramangagency/craftagram#20]
Craftagram no longer displayes anything. So I hit the "Authorize Craft" button:

This results in this error:

> error_type | "OAuthException"
> code | 400
> error_message | "Invalid scope: []"

What's the problem here?

Craftagram 1.0.5
Craft 3.4.25

**Comment by joshua-martin** [comment]
The latest version of craftagram is 1.2.4. If you update do you still have the same issues?

**Comment by kaspar-allenbach** [comment]
Hold on…………… Jup

**Comment by joshua-martin** [comment]
The issue is likely to do with your setup of instagram.

When you click Authorise Craft, what URL do you get redirected to?

**Comment by kaspar-allenbach** [comment]
`https://www.instagram.com/oauth/authorize?client_id=644537799463295&redirect_uri=https://mydoamin.com//actions/craftagram/default/auth&scope=user_profile,user_media&response_type=code`

**Comment by joshua-martin** [comment]
Have you added an instagram tester as outlined in steps 7/8?

**Comment by kaspar-allenbach** [comment]
jup 
![Bildschirmfoto 2020-08-05 um 15 45 15](https://user-images.githubusercontent.com/762213/89420209-aed8c580-d732-11ea-88bb-e2261e660e3d.png)

![Bildschirmfoto 2020-08-05 um 15 46 23](https://user-images.githubusercontent.com/762213/89420323-d4fe6580-d732-11ea-9243-3afe84d26593.png)

**Comment by joshua-martin** [comment]
Is your app in development mode in Facebook Developers?

**Comment by kaspar-allenbach** [comment]
No

<img width="261" alt="Bildschirmfoto 2020-08-05 um 15 49 58" src="https://user-images.githubusercontent.com/762213/89420672-55bd6180-d733-11ea-84d7-b9f067f3d1d9.png">

**Comment by joshua-martin** [comment]
Have you enabled `instagram_graph_user_profile` as outlined in the README?

> You can ignore App Review, but please note that if you plan to publish this app, then you will need to turn on the instagram_graph_user_profile option, as this is required for creating a long access token.

**Comment by kaspar-allenbach** [comment]
No. This is disabled. As I understand your docs. This is not necessary.

**Comment by joshua-martin** [comment]
> If you plan to publish this app, you will need to turn on the `instagram_graph_user_profile` option

You've made your app live, so you will need this turned on. Either select this option or set your app back to in development.

**Comment by kaspar-allenbach** [comment]
Does this work without verification? If I enable instagram_user_profile.
There is a message which states that verification is disabled for individuals due to covid ??

**Comment by joshua-martin** [comment]
I'm afraid I can't answer that–if the app is already verified Facebook might not require re-verification.

For what it's worth, we haven't bothered to publish any apps because you can continue to use the integration indefinitely when the app is set to *In Development*.

**Comment by kaspar-allenbach** [comment]
Ehhm. What?

So I should leave it in Development mode?

**Comment by kaspar-allenbach** [comment]
If I leave it to developement mode the error message changes to:


`error_message | "Insufficient developer role"`

**Comment by joshua-martin** [comment]
You can leave the app in Development mode, yes. The only reason to make apps live is to gain deeper insights on data, such as the information on users interacting with the app integrations like Pages and Ads. None of this is relevant for the connector to instagram.

That error message has already been covered in #16. It sounds like you should just create a new app and follow the configuration steps again, and leave the app as *Development*.

**Comment by velislav7** [comment]
> Have you added an instagram tester as outlined in steps 7/8?

That helped me, thank you
