### ISSUE TITLE
403 Forbidden on images from Instagram Feed

### ISSUE THREAD

**Issue by brianrivet** [scaramangagency/craftagram#21]
Hi,

I'm using Craftagram 1.2.1 with Craft 3.4.30. I'm getting a 403 Forbidden response on my feed images. This is a recent development because it was working a few days ago. Can you help me to resolve?

Thanks!

Brian

**Comment by brianrivet** [comment]
The response from the Instagram API says "URL Signature Expired" if that helps.

**Comment by joshua-martin** [comment]
@brianrivet Have you set up a cron job to [refresh your long access token](https://github.com/scaramangagency/craftagram#keeping-your-token-active)? Tokens are only active for 60 days.

**Comment by brianrivet** [comment]
Hi Joshua,

You can close this ticket. I do have the cron job set up, but I think the problem was something else unrelated to the plugin. The home page template broke down temporarily for some reason but it came back up a short while later and the feed is working again.

Thanks!

**Comment by ColinTravis** [comment]
Actually, I'm having this issue as well, but specifically only with Instagram videos, and only overnight. We do have this specific page it appears on being cached with Blitz, and I'm wondering if that has something to do with it.

**Comment by smaniren** [comment]
i just added the plugin and i have the same problem. The image urls are fetched as expected. I can access the images when i just add the url to the browser. But used in the image tag, the images wont load because of a 403 error.

**Comment by jsmrtn** [comment]
Yes, pages cached with Blitz will need to have their cache rotated. The URL signature does expire per #65.
