### ISSUE TITLE
Long Access Token as a environement variable?

### ISSUE THREAD

**Issue by kaspar-allenbach** [scaramangagency/craftagram#22]
It would be nice to store the long Access token as a variable in the `.env`

**Comment by joshua-martin** [comment]
@kaspar-allenbach For what purpose? The plugin stores the long access token in the DB so it isn't tracked by git, and the long access token is generated programatically by the plugin, so you wouldn't know the token up front to store it in an environment variable.

**Comment by kaspar-allenbach** [comment]
Hm. Yeah you are right. I tought so it is stored everything in the same location and not all over the place.
