### ISSUE TITLE
Setup instructions unclear

### ISSUE THREAD

**Issue by vibze** [scaramangagency/craftagram#27]
Hello. We are trying to use the plugin in craft website to display several images in the footer. But we cannot proceed through step 5 because we dont have Instagram under products menu. I can see the "Business api settings" but it doesnt offer any of the stuff mentioned in the instructions.

![Untitled](https://user-images.githubusercontent.com/417557/93760053-230cf100-fc2d-11ea-9e6d-8f3948807268.png)

**Comment by joshua-martin** [comment]
@vibze On the popup which have you selected? I think you'll need to select _For Everything Else_ for your app, not _Manage Business Integrations_.

Business Integrations will force you down the Graph API and not Basic Display API. I've updated the README to cover this.

**Comment by vibze** [comment]
Thanks!

**Comment by vibze** [comment]
I am getting this error when I click the Authorise Craft button. Can you help me please?
![image](https://user-images.githubusercontent.com/417557/93844737-0c63aa00-fcc0-11ea-8c81-50ff2982eea1.png)
