### ISSUE TITLE
Authorise Craft button doesn't work if Craft is located in a subdirectory.

### ISSUE THREAD

**Issue by cloudgrayau** [scaramangagency/craftagram#32]
Line 80 in /src/templates/settings/index.twg:
window.location.href = '/actions/craftagram/default/handle-auth?client_id=' + $appId;

I would recommend changing this to:
window.location.href = '{{ siteUrl }}actions/craftagram/default/handle-auth?client_id=' + $appId;

**Comment by joshua-martin** [comment]
@cloudgrayau Just to clarify, you mean in such a way that `https://www.website.com` is not Craft, and instead `https://www.website.com/folder` contains Craft?

**Comment by cloudgrayau** [comment]
Yep, that’s right.

--
Aaron Gray

On 29 October 2020 at 7:08:21 pm, Joshua Martin (notifications@github.com<mailto:notifications@github.com>) wrote:

@cloudgrayau<https://github.com/cloudgrayau> Just to clarify, you mean in such a way that https://www.website.com is not Craft, and instead https://www.website.com/folder contains Craft?
