### ISSUE TITLE
Authorize Error

### ISSUE THREAD

**Issue by laurabennett** [scaramangagency/craftagram#42]
I had this working but am not able to renew after 60 days. I have upgraded Craft but no changes to the Instagram account or the website url. Here is the stack trace I get when I go to the redirect uri. /actions/craftagram/default/auth

PHP 7.4.16
Craft 3.6.13
Craftagram 1.4.4

yii\base\ErrorException: Undefined index: query in /home/settlersgreen/webapps/dev/vendor/scaramangagency/craftagram/src/controllers/DefaultController.php:70
Stack trace:
#0 /home/settlersgreen/webapps/dev/vendor/craftcms/cms/src/web/ErrorHandler.php(77): yii\base\ErrorHandler->handleError()
#1 /home/settlersgreen/webapps/dev/vendor/scaramangagency/craftagram/src/controllers/DefaultController.php(70): craft\web\ErrorHandler->handleError()
#2 [internal function]: scaramangagency\craftagram\controllers\DefaultController->actionAuth()
#3 /home/settlersgreen/webapps/dev/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#4 /home/settlersgreen/webapps/dev/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#5 /home/settlersgreen/webapps/dev/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#6 /home/settlersgreen/webapps/dev/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction()
#7 /home/settlersgreen/webapps/dev/vendor/craftcms/cms/src/web/Application.php(279): yii\base\Module->runAction()
#8 /home/settlersgreen/webapps/dev/vendor/craftcms/cms/src/web/Application.php(582): craft\web\Application->runAction()
#9 /home/settlersgreen/webapps/dev/vendor/craftcms/cms/src/web/Application.php(258): craft\web\Application->_processActionRequest()
#10 /home/settlersgreen/webapps/dev/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#11 /home/settlersgreen/webapps/dev/web/index.php(21): yii\base\Application->run()
#12 {main}

**Comment by joshua-martin** [comment]
@laurabennett Sorry to hear your having issues–can you paste the full URL you get when you are being returned to the auth page from instagram?

**Comment by gjhead** [comment]
Here you go:
https://www.instagram.com/oauth/authorize?client_id=479148739995525&scope=user_profile,user_media&response_type=code&redirect_uri=https://www.premierprotein.com/actions/craftagram/default/auth&state=4

Now it is giving me this and a:

{"error_type": "OAuthException", "code": 400, "error_message": "Invalid redirect_uri"}
