### ISSUE TITLE
UI error

### ISSUE THREAD

**Issue by krisMoca** [scaramangagency/craftagram#44]
Hi I'm getting this error on one of our client's website.

![craftagram](https://user-images.githubusercontent.com/86084360/122482675-1c2cd680-d025-11eb-8255-0802aacd6978.PNG)

**Comment by joshua-martin** [comment]
What version are you running? It looks like it's not extending the CP layout, rather sending you to a unique template.

**Comment by krisMoca** [comment]
Craft 3.6.17 and Craftagram 1.4.5

**Comment by joshua-martin** [comment]
Is there any way you can `rm -rf vendor` and then re-run `composer install`? I cannot replicate this with the same version numbers as you, so I can only assume you have bad files in vendor.

**Comment by joshua-martin** [comment]
Stale issue so closing. Let me know if you're still having this issue.
