### ISSUE TITLE
Is there a way to optimize images?

### ISSUE THREAD

**Issue by laurabennett** [scaramangagency/craftagram#45]
It would be nice to have the ability to specify the size of the image returned.
Does Instagram provide a thumbnail option?

**Comment by joshua-martin** [comment]
Unfortunately not. We're just returning everything the API gives us from the media endpoint, see [here](https://developers.facebook.com/docs/instagram-basic-display-api/reference/media#fields). There is a thumbnail, but it's only provided if the media type is video.

Unfortunately Craft's native transforms do not work with remote URLs, so you would need to use something like [Imager X](https://plugins.craftcms.com/imager-x). You could always use it's predecessor [Imager](https://plugins.craftcms.com/imager), which is free, but that has been deprecated so if there are any issues you likely wouldn't get a fix.
