### ISSUE TITLE
Feed for multiple accounts

### ISSUE THREAD

**Issue by tobystokes** [scaramangagency/craftagram#48]
Is it possible to use Craftagram to show a feed for multiple instagram accounts?
Either combined into one, or as separate feeds - but on the same craft site?

**Comment by scaramanga-support** [comment]
HI @tobystokes 

As much as I hate to give no as an answer, unfortunately, we have to offer it in response to both your questions. However, I have flagged your message as a feature request and the dev team here at Scaramanga will discuss and consider this functionality.
