### ISSUE TITLE
resize images

### ISSUE THREAD

**Issue by pioneerdesign** [scaramangagency/craftagram#5]
Is there any way to resize images pulled from the Instagram feed? We're displaying them at about 250px but the images are about 1200px which causes a big performance hit.

**Comment by joshua-martin** [comment]
You would need to use a plugin that enables you to make transforms on remote URLs, like [Imager X](https://github.com/spacecatninja/craft-imager-x).

The basic display API only returns a single size image in `media_url` (unlike the previous version that returned named sizes), so there isn’t anything I can do in this plugin, unfortunately.
