### ISSUE TITLE
PHP Use

### ISSUE THREAD

**Issue by RickKukiela** [scaramangagency/craftagram#50]
I was thinking about using this for a client but rather than having the feed pull the images directly into the template on load, I was thinking of adding a CP panel via my module code where I could use this plugin to pull in their most recent posts to instagram, display them all with checkboxes, and a download button which would save the selected images as assets which would add them to a locally hosted gallery. Do you foresee any issues doing this type of integration with this plugin?

Also, is there any information on what resolution I can expect to receive? Is it always going to be the original image the uploaded? Or is it the small size image that shows up if I were just pull up their instagram account in my browser and download one directly as those version are pretty low res.

Thanks!

**Comment by joshua-martin** [comment]
Hey @RickKukiela,

There's no reason I can think of why you wouldn't be able to create a template and load it into the CP as wish. The plugin obviously only facilities the connection to the endpoint and the return of the data, but you would be able to essentially replicate what the `CraftagramVariable` functions do with `getInstagramFeed`

As to your question about the resolution, I'm afraid I can only point you at the [Instagram docs](https://developers.facebook.com/docs/instagram-basic-display-api/reference/media). To my recollection it will send you back a hi-res file, not a small thumbnail or a modal version that you get in the browser.
