### ISSUE TITLE
Width and height

### ISSUE THREAD

**Issue by josh-attwood** [scaramangagency/craftagram#53]
Hey! Plugin is fantastic and has really helped us out on a couple of projects we're currently developing so appreciate all your work!

This is more of a feature request than anything and not sure if it's possible.

It would be great if we were able to call the image width and height as separate attributes (if that's something that instagram makes available through their API) before the images are loaded in. There are a few cases where I use the images width and height to determine the container size before images are lazy loaded in (particularly useful to avoid using something like imagesLoaded when using masonry/isotope).

**Comment by joshua-martin** [comment]
Hey @josh-attwood,

Unfortunately it's not possible. We provide back the raw response from Instagram, and they do not allow you to send specific width and height attributes from their API.

You could perhaps use a plugin like Imager to grab the width/height from external asset URLs for use in masonry.

Kind regards
