### ISSUE TITLE
Craft 4 Update?

### ISSUE THREAD

**Issue by gjhead** [scaramangagency/craftagram#54]
Are there plans to update this plugin for Craft 4?

**Comment by joshua-martin** [comment]
@gjhead Yes there are, timescales are unknown at present, however.

**Comment by Mathias-Syversen** [comment]
+1 

currently the only thing keeping me from upgrading

**Comment by joshua-martin** [comment]
@gjhead @Mathias-Syversen There is a Craft 4 capable version of the plugin available on https://github.com/scaramangagency/craftagram/tree/v2, which you can use by updating your composer to `"scaramangagency/craftagram": "dev-v2"`

If you could update your plugin and beta test it quickly and let me know how you get on, that would be great, as I can then push the updated version to the plugin store.

**Comment by richhayler** [comment]
+1 for Craft 4 support

**Comment by joshua-martin** [comment]
@richhayler see above comment, a Craft 4 compatible version is available on v2 branch.
