### ISSUE TITLE
Error installing when used with project config

### ISSUE THREAD

**Issue by JJimmyFlynn** [scaramangagency/craftagram#6]
When installing the plugin on a deployed environment via the `project-config/sync` command, the command errors with the output:
`Installing plugin "craftagram" ... error: Calling unknown method: yii\console\Response::redirect()`

Running the command again results in a successful install.

Thanks for all the hard work on wrangling Instagram!

**Comment by joshua-martin** [comment]
Fixed in [1.0.6](https://github.com/scaramangagency/craftagram/releases/tag/1.0.6). Thanks.
