### ISSUE TITLE
Caching causing instagram feed URL signature expired error

### ISSUE THREAD

**Issue by splendidrob** [scaramangagency/craftagram#65]
Just wandering what is the correct way to cache the output. I've found an error occurring sometimes where the image links are broken - following the links directly results in the error: instagram feed URL signature expired.

Clearing the cache seems to fix...

My instagram include is inside of a cached matrix block. Any guidance much appreciated! Many thanks!

**Comment by joshua-martin** [comment]
Hey Rob,

The best option would be to refresh your cache occasionally to ensure the URL signature doesn't expire, I'm not sure what the expiry time is but maybe expire it every day or 12 hours or whatever the life of the token is.

Unfortunately there's not much more I can suggest, as suggest that the expiry comes from Meta and not from us (y)

Thanks
