### ISSUE TITLE
Invalid Request: Request parameters are invalid: Invalid redirect_uri

### ISSUE THREAD

**Issue by perry-garvin** [scaramangagency/craftagram#69]
I've gone through the instructions and I've double checked everything but when I click "Authorize Craft" I get this error:

`Invalid Request: Request parameters are invalid: Invalid redirect_uri`

In the Facebook app configuration I've checked and my domain URI is correct for Client OAuth Settings:

`https://mywebsite.org/actions/craftagram/default/auth`

What am I doing wrong?

**Comment by scaramanga-support** [comment]
I haven’t got as detailed knowledge of Craftagram as my colleague, but whenever this issue has cropped up before it is usually to do with a mismatch between the URL in Craft and Facebook.

Check for things like a trailing slash or missing www protocol.

See this comment https://github.com/scaramangagency/craftagram/issues/29#issuecomment-704137215

Hopefully, this helps.

**Comment by perry-garvin** [comment]
I tried and tried, going through the Craftagram documentation step by step, over and over, but I just couldn’t get it to work. I kept getting error `Invalid Request: Request parameters are invalid: Invalid redirect_uri `. 

But I ultimately did get the plugin to work but through a different means: I went to my Facebook app’s setting page (the one where Craftagram documentation has you put in your Valid OAuth Redirect URI). I clicked “Generate Token” next to my authorized Instagram Test User, copied the token, and pasted it into Craftagram’s Long Access Token field. Save. Now it works.

**Comment by jsmrtn** [comment]
I'll run through the setup steps and see if I can replicate this issue.

**Comment by jsmrtn** [comment]
Hey @perry-garvin. I've just ran through the setup procedure with a brand new app (updating the steps to the new workflow as the process is a little different since the documentation was created) and it generated the long access token correctly. I wonder if there was just an mis-configuration somewhere for you. Glad you managed to get it sorted generating the token manually, though!
