### ISSUE TITLE
Craft 5 compatibility

### ISSUE THREAD

**Issue by BenHMatrix** [scaramangagency/craftagram#70]
Will this plugin be updated to support Craft 5?

**Comment by jsmrtn** [comment]
Compatibility for Craft 5 is available via [v3](https://github.com/jsmrtn/craftagram/tree/v3).

I'm in the process of taking ownership of the plugin through the plugin store and abandoning the previous version, so please bear with me.

**Comment by jsmrtn** [comment]
You can now install `@jsmrtn/craftagram@3.0.0` to gain Craft 5 compatibility. Your existing licenses should remain in place.
