### ISSUE TITLE
Long Access Token does not get created?

### ISSUE THREAD

**Issue by bartrylant** [scaramangagency/craftagram#71]
When entering the Instagram App ID and Secret (after following all the setup steps) no token gets generated when clicking "Authorise Craft". It does work on my local development server, but not on my production server. Does this have something to do with setting "allow admin changes" to false on production?

**Comment by jsmrtn** [comment]
Hmm. Doesn't look like it – when you say no token gets generated, you mean it just returns to Craft from the redirect from Instagram with no token? I've tested (albeit locally) by setting environment to production and disabling admin changes and the token still gets pulled in.
