### ISSUE TITLE
Add Alt Text To Images

### ISSUE THREAD

**Issue by ec-propaganda** [scaramangagency/craftagram#72]
Is there a way to pull captions from the posts and use them as alt text on the img tags? My client's ADA audit is flagging their instagram feed and telling us to add alt tags to images, but I can't find a setting or any documentation about how to do it. TIA!

**Comment by jsmrtn** [comment]
Hi @ec-propaganda,

Apologies for the delay. `caption` should already be available to you in the returned JSON response.


```
{% set craftagram = craft.craftagram.getInstagramFeed(10) %}

{% for item in craftagram.data %}
    <img src={{item.media_url}} alt={{item.caption}} />
{% endfor %}
```

Thanks!

**Comment by samuel-clara** [comment]
I'm getting the following error:

`Neither the property "caption" nor one of the methods "caption()", "getcaption()"/"iscaption()"/"hascaption()" or "__call()" exist and have public access in class "stdClass".`
