### ISSUE TITLE
Losing access to IG after Dec 4, 2024

### ISSUE THREAD

**Issue by mrseth01** [scaramangagency/craftagram#74]
The IG documentation reads "The Instagram Basic Display API will be discontinued on December 4th, 2024. After that date, access to the Instagram Basic Display API and your historical usage of it will no longer be available. Download your information now if you'd like to keep it."

Is there a plan or opportunity for continuing support post this date?

**Comment by jsmrtn** [comment]
Yes — I’m working on updating to the Instagram API rather than the basic display API at present 👍🏼

**Comment by jsmrtn** [comment]
@mrseth01 There is a `4.0.0-beta` release available if you wanted to get ahead and be a beta tester for me :)

You can read the updated README at https://github.com/jsmrtn/craftagram/tree/v4

**Comment by jsmrtn** [comment]
Deployed in 4.0.0.
