### ISSUE TITLE
4.0.0 version Authorise Craft not working

### ISSUE THREAD

**Issue by samuel-clara** [scaramangagency/craftagram#75]
Using the 4.0.0 release and configuring craftagram, clicking on Authorise Craft and "authorizing" on the Instagram side does not populate the "Long Access Token" field as described in the documentation.

I've checked that I was logged in to the correct account before trying to authenticate. I've tried this on multiple environments with no success.

**Comment by tobystokes** [comment]
I think i'm getting the same - tried being logged into instagram, tried being not logged into instagram.

I note the body of the page instagram returns says Error, but the page title says 'Page not found' but more revealingly, it returns it with a status code of `429 Too Many Requests` so I suspect that the simplest fix is to try again only after an hour or so...

**Comment by tobystokes** [comment]
Worth pointing out that as a workaround, you can generate a long access token from the Facebook app admin page directly. 
Under the 'API setup with Instagram business login', once you have linked an account, you can 'Generate access tokens'

**Comment by jsmrtn** [comment]
So to clarify @samuel-clara @tobystokes you don't get any errors, but when you are returned to your craft installation after you've hit `Allow` on instagram, no access token is populated in Craft?

**Comment by jsmrtn** [comment]
I've cut a new release `4.0.1` that adds better debugging. It should output any errors into `storage/logs/craftagram-{X.X.X}.log`.

If you could try to run through the process again and see where it might be falling over, that would be great. You shouldn't need to set anything up again, it should let you re-authorize through the same embed url and you'll just get given a new token.

**Comment by jsmrtn** [comment]
Feel free to comment if the issue is still ongoing. As an aside, I wonder if this might have been to do with #79.

**Comment by tobystokes** [comment]
I just tried using 4.1.0
This time, I got the more useful error as a json response from instagram
```
{
"error_type": "OAuthException",
"code": 400,
"error_message": "Invalid redirect_uri"
}
```

hmm, and the URL of that message was from:
https://www.instagram.com/oauth/authorize?enable_fb_login=0&client_id=XXX&redirect_uri=%2Fuk%2Factions%2Fcraftagram%2Fdefault%2Fauth&response_type=code&scope=instagram_business_basic%2Cinstagram_business_manage_messages%2Cinstagram_business_manage_comments%2Cinstagram_business_content_publish&state=1&logger_id=XXX
which looks like `BASE_URL` is missing?

**Comment by jsmrtn** [comment]
So to clarify, the `redirect_uri` prop was just set to `%2Fuk...`?

What is your baseUrl set to under `Craft::parseEnv(Craft::$app->sites->primarySite->baseUrl)`? As this is the variable that is used to populate that query param

**Comment by tobystokes** [comment]
Yep, my `primarySite.baseUrl` = `/uk`
So it's really just the basePath not a full Url, hmm, it works fine for my other needs, maybe a hangover from this sites Craft 2 origins. Is this unusual?
Doesn't seem to have any side effects if I set it to `$BASE_URL/uk` instead, which does output the actual URL, so I could try that if you reckon that's the cause...

**Comment by jsmrtn** [comment]
It's unusual to me, but that doesn't mean it's unusual to other developers I suppose. 

This was the same way the `baseUrl` was grabbed in previous in the previous version, too, so I wonder if you using this plugin in your Craft 4 instance? If so, would have to suggest that perhaps the full URL used to be populated by default into `baseUrl` and now it isn't.

**Comment by ammonhaggerty** [comment]
Jumping on this thread since it seems related. I had it set up and working and it recently stopped. It's possible it coincided with my token expiring. I'm struggling getting it working again as the documentation seems out of sync with FB and IG settings UI. Any suggestions would be appreciated!

Also getting `{"error_type": "OAuthException", "code": 400, "error_message": "Invalid redirect_uri"}`. 

Logs:
`[2024-12-09 22:05:07] getInstagramMediaIDs:265: $instaProfileInfo error: {"error":{"message":"Error validating access token: The session has been invalidated because the user changed their password or Facebook has changed the session for security reasons.","type":"OAuthException","code":190,"fbtrace_id":"AXJI4VSZefwiZWhiQ4MZBqJ"}}`

**Comment by bartrylant** [comment]
Having the same issue. Cannot get my instagram feed on my page because my token cannot be renewed.

**Comment by jsmrtn** [comment]
@ammonhaggerty @bartrylant 

Can you clarify if you have created a brand new app per the README that was functioning and has now ceased to, or you have updated to 4.0.0 and your existing apps have stopped working?

**Comment by bartrylant** [comment]
I am on 4.1.0 (updated) and the existing feed stopped working.

**Comment by jsmrtn** [comment]
Per the [4.0.0 release notes](https://github.com/jsmrtn/craftagram/releases/tag/4.0.0) the basic display API has been switched off, you will need to create a new app per the instructions in the README.

**Comment by bartrylant** [comment]
Ok. Well I succeeded until sep 7. This gets me here:

<img width="712" alt="Scherm­afbeelding 310" src="https://github.com/user-attachments/assets/73544b94-bcc9-4e16-9336-6125e9e3ca3c">

**Comment by ammonhaggerty** [comment]
@jsmrtn - I wasn't paying attention if the original set up was pre-4.0. It was set up in August in a Craft 5 project. It sounds like there was a breaking change that requires a clean setup? If this is the case, I'd make it a bit more clear in the README. Ideally I wouldn't need to start over as I don't have access to the FB account (clients), although I do have access to the IG account.

**Comment by jsmrtn** [comment]
I’ll add a note to the top of the README to highlight this for sure.

Unfortunately we don’t have a choice but to recreate the app with the new setup, as the old Basic Display applications that were created will no longer be supported as they’ve switched this functionality off.

**Comment by ammonhaggerty** [comment]
@jsmrtn - looks like the Instagram Basic Display API has been deprecated. Please update the setup guide. I'm having trouble getting it to work with just the Instagram API. https://developers.facebook.com/blog/post/2024/09/04/update-on-instagram-basic-display-api/

**Comment by jsmrtn** [comment]
@ammonhaggerty v4.0.0 handles the deprecation and moves from the Basic Display to the Instagram API. I'm unsure what you're asking me to update, the setup guide in the README already covers how to handle creation of an app that interfaces with the Instagram API.

**Comment by ammonhaggerty** [comment]
Followup — I was able to get it to work by choosing a Business account, rather than Consumer. Documentation needs updating. Thanks!

**Comment by jsmrtn** [comment]
I'm unsure where you have read that you need to select a `Consumer` account. Step 4 of the [README](https://github.com/jsmrtn/craftagram?tab=readme-ov-file#set-up) states you must select a `Business` account. Either way, I'm happy you have got it sorted.
