### ISSUE TITLE
Docs - adding instagram app doesn't match with the documentation

### ISSUE THREAD

**Issue by splendidrob** [scaramangagency/craftagram#77]
After running the lates updates our previously setup instagram apps stopped working as mentioned :)

I've been going through the docs to connect up a new account via the facebook developer account but the last two steps in the docs dont relate to anything i can see in the facebook setup:

```
Enter your Primary Site base URL, appended with /actions/craftagram/default/auth (i.e. https://www.yourwebsite.com/actions/craftagram/default/auth) into Set up Instagram business login.
```
I couldn't see anywhere to add this during the process - after adding an account under generate access tokens we just select the Instagram account and choose connect. No option to add a base URL

```
Copy Embed URL, Instagram app ID and Instagram app secret for use in Configuring craftagram below.
```
The Embed URL doesnt exist in our account anywhere...

Any help much appreciated in order to get this working again!

**Comment by jsmrtn** [comment]
Hey @splendidrob 

It's available under `Instagram` > `API Setup with Instagram Login`

<img width="1148" alt="Screenshot 2024-11-20 at 13 03 57" src="https://github.com/user-attachments/assets/b9b589b4-7e37-466c-98d5-e2b9a5d9fa17">

**Comment by splendidrob** [comment]
Muppet!! Thank you :D

**Comment by jsmrtn** [comment]
No worries mate! Let me know if you have any trouble as some consumers have had issues with the authorisation route per #75 👍🏼

**Comment by jsmrtn** [comment]
No worries mate! Let me know if you have any trouble as some consumers have had issues with the authorisation populating the tokens per #75 👍🏼
