### ISSUE TITLE
Can't seem to install plugin

### ISSUE THREAD

**Issue by helenc77** [scaramangagency/craftagram#78]
Hi guys, I'm getting a weird error when I try and install via the plugin store (install button). This is odd because I installed it the other day (then completely stuffed up the config and had to start all over again lol) and it worked fine then. 

<img width="1792" alt="image" src="https://github.com/user-attachments/assets/59013692-1123-4e72-8895-7aa7ae6100d3">

**Comment by helenc77** [comment]
I also just remembered I should delete the vendor folder and composer install when faced with problems like this, so I've done that and used a fresh db, but I'm still getting the problem for some reason?

**Comment by jsmrtn** [comment]
Hmmm. Seems odd that it would error even with a fresh DB. Are you able to `Troubleshoot` or otherwise check your logs to see if there's a more verbose error being saved anywhere?

**Comment by helenc77** [comment]
Thanks for the reply. I was doing my database restore by doing a pull from Servd and it occurred to me that it might not be completely emptying the existing db, so I did it manually and we now have a successful plugin install! I'm still having some configuration issues but I'll post this as another issue because it is really.
