### ISSUE TITLE
Debugging locally

### ISSUE THREAD

**Issue by tobystokes** [scaramangagency/craftagram#8]
Is it possible to copy the access token to a local dev env to see debug output?
I ask because although i'm fairly sure my app setup is correct (I can authorise and it returned a long access token), i get no output on the live site.
if i copy the access token back to my local site, 
`{{ dump(craft.craftagram.getInstagramFeed()) }}` I just get NULL.

**Comment by joshua-martin** [comment]
In your app setup in point 6 of the README you should be able to add your local dev URL to the permitted callback URLs. Then you can manually authorise in the local admin which will give you a long-access token.

**Comment by tobystokes** [comment]
Thanks!
Of course, i was assuming that instagram needed access to that as a public URL but if it's just used as somewhere to redirect you to once the token is retrieved, then it will/does work.
